# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EachOther' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'RxSwift'
pod 'RxCocoa'
pod 'JTAppleCalendar', '~> 7.0'
pod 'DLRadioButton', '~> 1.4'
pod 'Firebase/Core'
  # Pods for EachOther

  target 'EachOtherTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
